language: ruby
rvm:
  - 2.5

install:
  - wget https://rubygems.org/downloads/json-1.8.3.gem
  - gem install --local json-1.8.3.gem
  - gem install bundler
  - cd site/zh
  - bundle install --deployment

script:
  - jekyll build

after_script:
  - cd content
  - git init
  - git config user.name ${GH_UN}
  - git config user.email ${GH_EMAIL}
  - git add -A
  - git commit -am "$(date "+%Y-%m-%d %H:%M:%S")"
  - git push "https://${GH_TOKEN}@github.com/${GH_USER}/${GH_REPO}.git" master:${GH_BRANCH} -f

env:
  global:
    - GH_UN=jiangzhonglian
    - GH_EMAIL=jiang-s@163.com
    - GH_USER=apachecn
    - GH_REPO=beam-site-zh
    - GH_BRANCH=gh-pages
